name: Deploy to Fly.io

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.js'
      - 'package.json'
      - 'package-lock.json'
      - 'public/**'
      - 'lib/**'
      - 'server.js'
      - 'Dockerfile'
      - 'fly.toml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --remote-only
