# Fly.io app configuration for SeedSphere Stremio Addon
# If you already created an app with `flyctl launch`, replace the app name below to match it.
app = "seedsphere"

# Optional: set to your preferred region, or omit to let Fly choose
# primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 55025
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]
