// Mocks generated by Mockito 5.4.6 from annotations
// in gardener/test/core/stream_resolver_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gardener/core/config_manager.dart' as _i2;
import 'package:gardener/core/providers/debrid_provider.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConfigManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigManager extends _i1.Mock implements _i2.ConfigManager {
  MockConfigManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get sortBy =>
      (super.noSuchMethod(
            Invocation.getter(#sortBy),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#sortBy),
            ),
          )
          as String);

  @override
  bool get excludeCam =>
      (super.noSuchMethod(Invocation.getter(#excludeCam), returnValue: false)
          as bool);

  @override
  bool get exclude3D =>
      (super.noSuchMethod(Invocation.getter(#exclude3D), returnValue: false)
          as bool);

  @override
  bool get preferHDR =>
      (super.noSuchMethod(Invocation.getter(#preferHDR), returnValue: false)
          as bool);

  @override
  String get includeRegex =>
      (super.noSuchMethod(
            Invocation.getter(#includeRegex),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#includeRegex),
            ),
          )
          as String);

  @override
  String get excludeRegex =>
      (super.noSuchMethod(
            Invocation.getter(#excludeRegex),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#excludeRegex),
            ),
          )
          as String);

  @override
  bool get autoProxy =>
      (super.noSuchMethod(Invocation.getter(#autoProxy), returnValue: false)
          as bool);

  @override
  int get maxTrackers =>
      (super.noSuchMethod(Invocation.getter(#maxTrackers), returnValue: 0)
          as int);

  @override
  bool get preferEncrypted =>
      (super.noSuchMethod(
            Invocation.getter(#preferEncrypted),
            returnValue: false,
          )
          as bool);

  @override
  bool get normalizeHttps =>
      (super.noSuchMethod(
            Invocation.getter(#normalizeHttps),
            returnValue: false,
          )
          as bool);

  @override
  String get trackerVariant =>
      (super.noSuchMethod(
            Invocation.getter(#trackerVariant),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#trackerVariant),
            ),
          )
          as String);

  @override
  String get customTrackersUrl =>
      (super.noSuchMethod(
            Invocation.getter(#customTrackersUrl),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#customTrackersUrl),
            ),
          )
          as String);

  @override
  bool get backgroundDownload =>
      (super.noSuchMethod(
            Invocation.getter(#backgroundDownload),
            returnValue: false,
          )
          as bool);

  @override
  bool get onlyShowCached =>
      (super.noSuchMethod(
            Invocation.getter(#onlyShowCached),
            returnValue: false,
          )
          as bool);

  @override
  String get maxResolution =>
      (super.noSuchMethod(
            Invocation.getter(#maxResolution),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#maxResolution),
            ),
          )
          as String);

  @override
  List<String> get prioritizedLanguages =>
      (super.noSuchMethod(
            Invocation.getter(#prioritizedLanguages),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get enableTorrentio =>
      (super.noSuchMethod(
            Invocation.getter(#enableTorrentio),
            returnValue: false,
          )
          as bool);

  @override
  bool get enableYts =>
      (super.noSuchMethod(Invocation.getter(#enableYts), returnValue: false)
          as bool);

  @override
  bool get enableEztv =>
      (super.noSuchMethod(Invocation.getter(#enableEztv), returnValue: false)
          as bool);

  @override
  bool get enableNyaa =>
      (super.noSuchMethod(Invocation.getter(#enableNyaa), returnValue: false)
          as bool);

  @override
  bool get enable1337x =>
      (super.noSuchMethod(Invocation.getter(#enable1337x), returnValue: false)
          as bool);

  @override
  bool get enablePirateBay =>
      (super.noSuchMethod(
            Invocation.getter(#enablePirateBay),
            returnValue: false,
          )
          as bool);

  @override
  bool get enableTorrentGalaxy =>
      (super.noSuchMethod(
            Invocation.getter(#enableTorrentGalaxy),
            returnValue: false,
          )
          as bool);

  @override
  bool get enableTorlock =>
      (super.noSuchMethod(Invocation.getter(#enableTorlock), returnValue: false)
          as bool);

  @override
  bool get enableMagnetDL =>
      (super.noSuchMethod(
            Invocation.getter(#enableMagnetDL),
            returnValue: false,
          )
          as bool);

  @override
  bool get enableAniDex =>
      (super.noSuchMethod(Invocation.getter(#enableAniDex), returnValue: false)
          as bool);

  @override
  bool get enableTokyoTosho =>
      (super.noSuchMethod(
            Invocation.getter(#enableTokyoTosho),
            returnValue: false,
          )
          as bool);

  @override
  bool get enableZooqle =>
      (super.noSuchMethod(Invocation.getter(#enableZooqle), returnValue: false)
          as bool);

  @override
  bool get enableRutor =>
      (super.noSuchMethod(Invocation.getter(#enableRutor), returnValue: false)
          as bool);

  @override
  String get validationMode =>
      (super.noSuchMethod(
            Invocation.getter(#validationMode),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#validationMode),
            ),
          )
          as String);

  @override
  bool get probeProviders =>
      (super.noSuchMethod(
            Invocation.getter(#probeProviders),
            returnValue: false,
          )
          as bool);

  @override
  int get probeTimeoutMs =>
      (super.noSuchMethod(Invocation.getter(#probeTimeoutMs), returnValue: 0)
          as int);

  @override
  int get providerFetchTimeoutMs =>
      (super.noSuchMethod(
            Invocation.getter(#providerFetchTimeoutMs),
            returnValue: 0,
          )
          as int);

  @override
  bool get swarmEnabled =>
      (super.noSuchMethod(Invocation.getter(#swarmEnabled), returnValue: false)
          as bool);

  @override
  int get swarmTopN =>
      (super.noSuchMethod(Invocation.getter(#swarmTopN), returnValue: 0)
          as int);

  @override
  bool get swarmMissingOnly =>
      (super.noSuchMethod(
            Invocation.getter(#swarmMissingOnly),
            returnValue: false,
          )
          as bool);

  @override
  int get swarmTimeoutMs =>
      (super.noSuchMethod(Invocation.getter(#swarmTimeoutMs), returnValue: 0)
          as int);

  @override
  bool get appendOriginalDesc =>
      (super.noSuchMethod(
            Invocation.getter(#appendOriginalDesc),
            returnValue: false,
          )
          as bool);

  @override
  bool get requireDetailsForOriginal =>
      (super.noSuchMethod(
            Invocation.getter(#requireDetailsForOriginal),
            returnValue: false,
          )
          as bool);

  @override
  bool get neuroLinkEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#neuroLinkEnabled),
            returnValue: false,
          )
          as bool);

  @override
  String get cortexProvider =>
      (super.noSuchMethod(
            Invocation.getter(#cortexProvider),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#cortexProvider),
            ),
          )
          as String);

  @override
  String get cortexModel =>
      (super.noSuchMethod(
            Invocation.getter(#cortexModel),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#cortexModel),
            ),
          )
          as String);

  @override
  double get cortexDetailLevel =>
      (super.noSuchMethod(
            Invocation.getter(#cortexDetailLevel),
            returnValue: 0.0,
          )
          as double);

  @override
  int get aiTimeoutMs =>
      (super.noSuchMethod(Invocation.getter(#aiTimeoutMs), returnValue: 0)
          as int);

  @override
  int get aiCacheTtlMs =>
      (super.noSuchMethod(Invocation.getter(#aiCacheTtlMs), returnValue: 0)
          as int);

  @override
  String get aiUserId =>
      (super.noSuchMethod(
            Invocation.getter(#aiUserId),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#aiUserId),
            ),
          )
          as String);

  @override
  String get orionUserId =>
      (super.noSuchMethod(
            Invocation.getter(#orionUserId),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#orionUserId),
            ),
          )
          as String);

  @override
  String get debridService =>
      (super.noSuchMethod(
            Invocation.getter(#debridService),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#debridService),
            ),
          )
          as String);

  @override
  set sortBy(String? val) => super.noSuchMethod(
    Invocation.setter(#sortBy, val),
    returnValueForMissingStub: null,
  );

  @override
  set excludeCam(bool? val) => super.noSuchMethod(
    Invocation.setter(#excludeCam, val),
    returnValueForMissingStub: null,
  );

  @override
  set exclude3D(bool? val) => super.noSuchMethod(
    Invocation.setter(#exclude3D, val),
    returnValueForMissingStub: null,
  );

  @override
  set preferHDR(bool? val) => super.noSuchMethod(
    Invocation.setter(#preferHDR, val),
    returnValueForMissingStub: null,
  );

  @override
  set includeRegex(String? val) => super.noSuchMethod(
    Invocation.setter(#includeRegex, val),
    returnValueForMissingStub: null,
  );

  @override
  set excludeRegex(String? val) => super.noSuchMethod(
    Invocation.setter(#excludeRegex, val),
    returnValueForMissingStub: null,
  );

  @override
  set autoProxy(bool? val) => super.noSuchMethod(
    Invocation.setter(#autoProxy, val),
    returnValueForMissingStub: null,
  );

  @override
  set maxTrackers(int? val) => super.noSuchMethod(
    Invocation.setter(#maxTrackers, val),
    returnValueForMissingStub: null,
  );

  @override
  set preferEncrypted(bool? val) => super.noSuchMethod(
    Invocation.setter(#preferEncrypted, val),
    returnValueForMissingStub: null,
  );

  @override
  set normalizeHttps(bool? val) => super.noSuchMethod(
    Invocation.setter(#normalizeHttps, val),
    returnValueForMissingStub: null,
  );

  @override
  set trackerVariant(String? val) => super.noSuchMethod(
    Invocation.setter(#trackerVariant, val),
    returnValueForMissingStub: null,
  );

  @override
  set customTrackersUrl(String? val) => super.noSuchMethod(
    Invocation.setter(#customTrackersUrl, val),
    returnValueForMissingStub: null,
  );

  @override
  set backgroundDownload(bool? val) => super.noSuchMethod(
    Invocation.setter(#backgroundDownload, val),
    returnValueForMissingStub: null,
  );

  @override
  set onlyShowCached(bool? val) => super.noSuchMethod(
    Invocation.setter(#onlyShowCached, val),
    returnValueForMissingStub: null,
  );

  @override
  set maxResolution(String? val) => super.noSuchMethod(
    Invocation.setter(#maxResolution, val),
    returnValueForMissingStub: null,
  );

  @override
  set prioritizedLanguages(List<String>? val) => super.noSuchMethod(
    Invocation.setter(#prioritizedLanguages, val),
    returnValueForMissingStub: null,
  );

  @override
  set enableTorrentio(bool? val) => super.noSuchMethod(
    Invocation.setter(#enableTorrentio, val),
    returnValueForMissingStub: null,
  );

  @override
  set enableYts(bool? val) => super.noSuchMethod(
    Invocation.setter(#enableYts, val),
    returnValueForMissingStub: null,
  );

  @override
  set enableEztv(bool? val) => super.noSuchMethod(
    Invocation.setter(#enableEztv, val),
    returnValueForMissingStub: null,
  );

  @override
  set enableNyaa(bool? val) => super.noSuchMethod(
    Invocation.setter(#enableNyaa, val),
    returnValueForMissingStub: null,
  );

  @override
  set enable1337x(bool? val) => super.noSuchMethod(
    Invocation.setter(#enable1337x, val),
    returnValueForMissingStub: null,
  );

  @override
  set enablePirateBay(bool? val) => super.noSuchMethod(
    Invocation.setter(#enablePirateBay, val),
    returnValueForMissingStub: null,
  );

  @override
  set enableTorrentGalaxy(bool? val) => super.noSuchMethod(
    Invocation.setter(#enableTorrentGalaxy, val),
    returnValueForMissingStub: null,
  );

  @override
  set enableTorlock(bool? val) => super.noSuchMethod(
    Invocation.setter(#enableTorlock, val),
    returnValueForMissingStub: null,
  );

  @override
  set enableMagnetDL(bool? val) => super.noSuchMethod(
    Invocation.setter(#enableMagnetDL, val),
    returnValueForMissingStub: null,
  );

  @override
  set enableAniDex(bool? val) => super.noSuchMethod(
    Invocation.setter(#enableAniDex, val),
    returnValueForMissingStub: null,
  );

  @override
  set enableTokyoTosho(bool? val) => super.noSuchMethod(
    Invocation.setter(#enableTokyoTosho, val),
    returnValueForMissingStub: null,
  );

  @override
  set enableZooqle(bool? val) => super.noSuchMethod(
    Invocation.setter(#enableZooqle, val),
    returnValueForMissingStub: null,
  );

  @override
  set enableRutor(bool? val) => super.noSuchMethod(
    Invocation.setter(#enableRutor, val),
    returnValueForMissingStub: null,
  );

  @override
  set validationMode(String? val) => super.noSuchMethod(
    Invocation.setter(#validationMode, val),
    returnValueForMissingStub: null,
  );

  @override
  set probeProviders(bool? val) => super.noSuchMethod(
    Invocation.setter(#probeProviders, val),
    returnValueForMissingStub: null,
  );

  @override
  set probeTimeoutMs(int? val) => super.noSuchMethod(
    Invocation.setter(#probeTimeoutMs, val),
    returnValueForMissingStub: null,
  );

  @override
  set providerFetchTimeoutMs(int? val) => super.noSuchMethod(
    Invocation.setter(#providerFetchTimeoutMs, val),
    returnValueForMissingStub: null,
  );

  @override
  set swarmEnabled(bool? val) => super.noSuchMethod(
    Invocation.setter(#swarmEnabled, val),
    returnValueForMissingStub: null,
  );

  @override
  set swarmTopN(int? val) => super.noSuchMethod(
    Invocation.setter(#swarmTopN, val),
    returnValueForMissingStub: null,
  );

  @override
  set swarmMissingOnly(bool? val) => super.noSuchMethod(
    Invocation.setter(#swarmMissingOnly, val),
    returnValueForMissingStub: null,
  );

  @override
  set swarmTimeoutMs(int? val) => super.noSuchMethod(
    Invocation.setter(#swarmTimeoutMs, val),
    returnValueForMissingStub: null,
  );

  @override
  set appendOriginalDesc(bool? val) => super.noSuchMethod(
    Invocation.setter(#appendOriginalDesc, val),
    returnValueForMissingStub: null,
  );

  @override
  set requireDetailsForOriginal(bool? val) => super.noSuchMethod(
    Invocation.setter(#requireDetailsForOriginal, val),
    returnValueForMissingStub: null,
  );

  @override
  set neuroLinkEnabled(bool? val) => super.noSuchMethod(
    Invocation.setter(#neuroLinkEnabled, val),
    returnValueForMissingStub: null,
  );

  @override
  set cortexProvider(String? val) => super.noSuchMethod(
    Invocation.setter(#cortexProvider, val),
    returnValueForMissingStub: null,
  );

  @override
  set cortexModel(String? val) => super.noSuchMethod(
    Invocation.setter(#cortexModel, val),
    returnValueForMissingStub: null,
  );

  @override
  set cortexDetailLevel(double? val) => super.noSuchMethod(
    Invocation.setter(#cortexDetailLevel, val),
    returnValueForMissingStub: null,
  );

  @override
  set aiTimeoutMs(int? val) => super.noSuchMethod(
    Invocation.setter(#aiTimeoutMs, val),
    returnValueForMissingStub: null,
  );

  @override
  set aiCacheTtlMs(int? val) => super.noSuchMethod(
    Invocation.setter(#aiCacheTtlMs, val),
    returnValueForMissingStub: null,
  );

  @override
  set aiUserId(String? val) => super.noSuchMethod(
    Invocation.setter(#aiUserId, val),
    returnValueForMissingStub: null,
  );

  @override
  set orionUserId(String? val) => super.noSuchMethod(
    Invocation.setter(#orionUserId, val),
    returnValueForMissingStub: null,
  );

  @override
  set debridService(String? val) => super.noSuchMethod(
    Invocation.setter(#debridService, val),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getRealDebridToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRealDebridToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> setRealDebridToken(String? val) =>
      (super.noSuchMethod(
            Invocation.method(#setRealDebridToken, [val]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getAllDebridApiKey() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDebridApiKey, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> setAllDebridApiKey(String? val) =>
      (super.noSuchMethod(
            Invocation.method(#setAllDebridApiKey, [val]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getOrionApiKey() =>
      (super.noSuchMethod(
            Invocation.method(#getOrionApiKey, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> setOrionApiKey(String? val) =>
      (super.noSuchMethod(
            Invocation.method(#setOrionApiKey, [val]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getPremiumizeApiKey() =>
      (super.noSuchMethod(
            Invocation.method(#getPremiumizeApiKey, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> setPremiumizeApiKey(String? val) =>
      (super.noSuchMethod(
            Invocation.method(#setPremiumizeApiKey, [val]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getApiKey(String? provider) =>
      (super.noSuchMethod(
            Invocation.method(#getApiKey, [provider]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> setApiKey(String? provider, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#setApiKey, [provider, key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [DebridProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDebridProvider extends _i1.Mock implements _i5.DebridProvider {
  MockDebridProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i3.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i4.Future<Map<String, dynamic>> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> addMagnet(
    String? magnet, {
    Map<String, dynamic>? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMagnet, [magnet], {#options: options}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> selectFiles(String? id, String? fileIds) =>
      (super.noSuchMethod(
            Invocation.method(#selectFiles, [id, fileIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getTorrentInfo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTorrentInfo, [id]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> unrestrictLink(String? link) =>
      (super.noSuchMethod(
            Invocation.method(#unrestrictLink, [link]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, bool>> checkAvailability(List<String>? hashes) =>
      (super.noSuchMethod(
            Invocation.method(#checkAvailability, [hashes]),
            returnValue: _i4.Future<Map<String, bool>>.value(<String, bool>{}),
          )
          as _i4.Future<Map<String, bool>>);
}
