// Mocks generated by Mockito 5.4.6 from annotations
// in router/test/p2p_node_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i10;

import 'package:dart_ipfs/src/core/data_structures/blockstore.dart' as _i2;
import 'package:dart_ipfs/src/core/data_structures/link.dart' as _i11;
import 'package:dart_ipfs/src/core/data_structures/peer.dart' as _i12;
import 'package:dart_ipfs/src/core/di/service_container.dart' as _i5;
import 'package:dart_ipfs/src/core/ipfs_node/ipfs_node.dart' as _i6;
import 'package:dart_ipfs/src/core/storage/datastore.dart' as _i4;
import 'package:dart_ipfs/src/protocols/dht/dht_client.dart' as _i3;
import 'package:dart_ipfs/src/protocols/pubsub/pubsub_message.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBlockStore_0 extends _i1.SmartFake implements _i2.BlockStore {
  _FakeBlockStore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDHTClient_1 extends _i1.SmartFake implements _i3.DHTClient {
  _FakeDHTClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatastore_2 extends _i1.SmartFake implements _i4.Datastore {
  _FakeDatastore_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeServiceContainer_3 extends _i1.SmartFake
    implements _i5.ServiceContainer {
  _FakeServiceContainer_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IPFSNode].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPFSNode extends _i1.Mock implements _i6.IPFSNode {
  @override
  String get peerId =>
      (super.noSuchMethod(
            Invocation.getter(#peerId),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#peerId),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#peerId),
            ),
          )
          as String);

  @override
  _i8.Stream<Map<String, dynamic>> get bandwidthMetrics =>
      (super.noSuchMethod(
            Invocation.getter(#bandwidthMetrics),
            returnValue: _i8.Stream<Map<String, dynamic>>.empty(),
            returnValueForMissingStub: _i8.Stream<Map<String, dynamic>>.empty(),
          )
          as _i8.Stream<Map<String, dynamic>>);

  @override
  List<String> get addresses =>
      (super.noSuchMethod(
            Invocation.getter(#addresses),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i2.BlockStore get blockStore =>
      (super.noSuchMethod(
            Invocation.getter(#blockStore),
            returnValue: _FakeBlockStore_0(
              this,
              Invocation.getter(#blockStore),
            ),
            returnValueForMissingStub: _FakeBlockStore_0(
              this,
              Invocation.getter(#blockStore),
            ),
          )
          as _i2.BlockStore);

  @override
  _i3.DHTClient get dhtClient =>
      (super.noSuchMethod(
            Invocation.getter(#dhtClient),
            returnValue: _FakeDHTClient_1(this, Invocation.getter(#dhtClient)),
            returnValueForMissingStub: _FakeDHTClient_1(
              this,
              Invocation.getter(#dhtClient),
            ),
          )
          as _i3.DHTClient);

  @override
  _i8.Future<List<String>> get connectedPeers =>
      (super.noSuchMethod(
            Invocation.getter(#connectedPeers),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<String> get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.getter(#publicKey)),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.getter(#publicKey)),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<String>> get pinnedCids =>
      (super.noSuchMethod(
            Invocation.getter(#pinnedCids),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Stream<_i9.PubSubMessage> get pubsubMessages =>
      (super.noSuchMethod(
            Invocation.getter(#pubsubMessages),
            returnValue: _i8.Stream<_i9.PubSubMessage>.empty(),
            returnValueForMissingStub: _i8.Stream<_i9.PubSubMessage>.empty(),
          )
          as _i8.Stream<_i9.PubSubMessage>);

  @override
  _i4.Datastore get datastore =>
      (super.noSuchMethod(
            Invocation.getter(#datastore),
            returnValue: _FakeDatastore_2(this, Invocation.getter(#datastore)),
            returnValueForMissingStub: _FakeDatastore_2(
              this,
              Invocation.getter(#datastore),
            ),
          )
          as _i4.Datastore);

  @override
  String get peerID =>
      (super.noSuchMethod(
            Invocation.getter(#peerID),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#peerID),
            ),
          )
          as String);

  @override
  _i8.Stream<String> get onNewContent =>
      (super.noSuchMethod(
            Invocation.getter(#onNewContent),
            returnValue: _i8.Stream<String>.empty(),
            returnValueForMissingStub: _i8.Stream<String>.empty(),
          )
          as _i8.Stream<String>);

  @override
  _i5.ServiceContainer get container =>
      (super.noSuchMethod(
            Invocation.getter(#container),
            returnValue: _FakeServiceContainer_3(
              this,
              Invocation.getter(#container),
            ),
            returnValueForMissingStub: _FakeServiceContainer_3(
              this,
              Invocation.getter(#container),
            ),
          )
          as _i5.ServiceContainer);

  @override
  List<String> resolvePeerId(String? peerIdStr) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePeerId, [peerIdStr]),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i8.Future<_i10.Uint8List?> cat(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#cat, [cid]),
            returnValue: _i8.Future<_i10.Uint8List?>.value(),
            returnValueForMissingStub: _i8.Future<_i10.Uint8List?>.value(),
          )
          as _i8.Future<_i10.Uint8List?>);

  @override
  _i8.Future<void> connectToPeer(String? multiaddr) =>
      (super.noSuchMethod(
            Invocation.method(#connectToPeer, [multiaddr]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> disconnectFromPeer(String? peerIdOrAddr) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectFromPeer, [peerIdOrAddr]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> resolveIPNS(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#resolveIPNS, [name]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#resolveIPNS, [name]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#resolveIPNS, [name]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> subscribe(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [topic]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> unsubscribe(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [topic]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> publish(String? topic, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [topic, message]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> addFile(_i10.Uint8List? data) =>
      (super.noSuchMethod(
            Invocation.method(#addFile, [data]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.method(#addFile, [data])),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.method(#addFile, [data])),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> addFileStream(_i8.Stream<List<int>>? dataStream) =>
      (super.noSuchMethod(
            Invocation.method(#addFileStream, [dataStream]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#addFileStream, [dataStream]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#addFileStream, [dataStream]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> addDirectory(Map<String, dynamic>? directoryContent) =>
      (super.noSuchMethod(
            Invocation.method(#addDirectory, [directoryContent]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#addDirectory, [directoryContent]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#addDirectory, [directoryContent]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  void setGatewayMode(_i6.GatewayMode? mode, {String? customUrl}) =>
      super.noSuchMethod(
        Invocation.method(#setGatewayMode, [mode], {#customUrl: customUrl}),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i10.Uint8List?> get(String? cid, {String? path = ''}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [cid], {#path: path}),
            returnValue: _i8.Future<_i10.Uint8List?>.value(),
            returnValueForMissingStub: _i8.Future<_i10.Uint8List?>.value(),
          )
          as _i8.Future<_i10.Uint8List?>);

  @override
  _i8.Future<List<_i11.Link>> ls(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#ls, [cid]),
            returnValue: _i8.Future<List<_i11.Link>>.value(<_i11.Link>[]),
            returnValueForMissingStub: _i8.Future<List<_i11.Link>>.value(
              <_i11.Link>[],
            ),
          )
          as _i8.Future<List<_i11.Link>>);

  @override
  _i8.Future<void> pin(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#pin, [cid]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> unpin(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#unpin, [cid]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> publishIPNS(String? cid, {required String? keyName}) =>
      (super.noSuchMethod(
            Invocation.method(#publishIPNS, [cid], {#keyName: keyName}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> importCAR(_i10.Uint8List? carFile) =>
      (super.noSuchMethod(
            Invocation.method(#importCAR, [carFile]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i10.Uint8List> exportCAR(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#exportCAR, [cid]),
            returnValue: _i8.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
            returnValueForMissingStub: _i8.Future<_i10.Uint8List>.value(
              _i10.Uint8List(0),
            ),
          )
          as _i8.Future<_i10.Uint8List>);

  @override
  _i8.Future<List<String>> findProviders(String? cid) =>
      (super.noSuchMethod(
            Invocation.method(#findProviders, [cid]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<void> requestBlock(String? cid, _i12.Peer? peer) =>
      (super.noSuchMethod(
            Invocation.method(#requestBlock, [cid, peer]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> resolveDNSLink(String? domainName) =>
      (super.noSuchMethod(
            Invocation.method(#resolveDNSLink, [domainName]),
            returnValue: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#resolveDNSLink, [domainName]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#resolveDNSLink, [domainName]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<Map<String, dynamic>> getHealthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getHealthStatus, []),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);
}
