// Mocks generated by Mockito 5.4.6 from annotations
// in router/test/scraper_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:router/tracker_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TrackerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrackerService extends _i1.Mock implements _i2.TrackerService {
  MockTrackerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> refreshMasterList() =>
      (super.noSuchMethod(
            Invocation.method(#refreshMasterList, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<String> getBestTrackers() =>
      (super.noSuchMethod(
            Invocation.method(#getBestTrackers, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> getSyncList() =>
      (super.noSuchMethod(
            Invocation.method(#getSyncList, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  void submitVotes(List<Map<String, dynamic>>? votes) => super.noSuchMethod(
    Invocation.method(#submitVotes, [votes]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<Map<String, dynamic>> optimize(List<String>? incoming) =>
      (super.noSuchMethod(
            Invocation.method(#optimize, [incoming]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Stream<Map<String, dynamic>> sweep(String? sourceUrl) =>
      (super.noSuchMethod(
            Invocation.method(#sweep, [sourceUrl]),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);
}
