// Mocks generated by Mockito 5.4.6 from annotations
// in router/test/tracker_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:router/db_service.dart' as _i2;
import 'package:router/health_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DbService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbService extends _i1.Mock implements _i2.DbService {
  @override
  void init(String? baseDir) => super.noSuchMethod(
    Invocation.method(#init, [baseDir]),
    returnValueForMissingStub: null,
  );

  @override
  void upsertTracker(String? url) => super.noSuchMethod(
    Invocation.method(#upsertTracker, [url]),
    returnValueForMissingStub: null,
  );

  @override
  void submitTrackerVote(String? url, bool? up, int? latency) =>
      super.noSuchMethod(
        Invocation.method(#submitTrackerVote, [url, up, latency]),
        returnValueForMissingStub: null,
      );

  @override
  List<String> getBestTrackers({int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(#getBestTrackers, [], {#limit: limit}),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> getTrackers({int? limit = 2000}) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackers, [], {#limit: limit}),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> getTrackersSync({int? limit = 2000}) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackersSync, [], {#limit: limit}),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  void createSession(String? sid, String? userId, int? ttlMs) =>
      super.noSuchMethod(
        Invocation.method(#createSession, [sid, userId, ttlMs]),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic>? getSession(String? sid) =>
      (super.noSuchMethod(
            Invocation.method(#getSession, [sid]),
            returnValueForMissingStub: null,
          )
          as Map<String, dynamic>?);

  @override
  List<Map<String, dynamic>> getSessions(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getSessions, [userId]),
            returnValue: <Map<String, dynamic>>[],
            returnValueForMissingStub: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  void deleteSession(String? sid) => super.noSuchMethod(
    Invocation.method(#deleteSession, [sid]),
    returnValueForMissingStub: null,
  );

  @override
  void revokeSession(String? sid) => super.noSuchMethod(
    Invocation.method(#revokeSession, [sid]),
    returnValueForMissingStub: null,
  );

  @override
  String? getBindingSecret(String? gardenerId, String? seedlingId) =>
      (super.noSuchMethod(
            Invocation.method(#getBindingSecret, [gardenerId, seedlingId]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  void createBinding(String? gardenerId, String? seedlingId, String? secret) =>
      super.noSuchMethod(
        Invocation.method(#createBinding, [gardenerId, seedlingId, secret]),
        returnValueForMissingStub: null,
      );

  @override
  void upsertGardener(String? gardenerId, {String? platform}) =>
      super.noSuchMethod(
        Invocation.method(#upsertGardener, [gardenerId], {#platform: platform}),
        returnValueForMissingStub: null,
      );

  @override
  void touchGardener(String? gardenerId) => super.noSuchMethod(
    Invocation.method(#touchGardener, [gardenerId]),
    returnValueForMissingStub: null,
  );

  @override
  void upsertSeedling(String? seedlingId) => super.noSuchMethod(
    Invocation.method(#upsertSeedling, [seedlingId]),
    returnValueForMissingStub: null,
  );

  @override
  void createLinkToken(String? token, String? gardenerId, int? ttlMs) =>
      super.noSuchMethod(
        Invocation.method(#createLinkToken, [token, gardenerId, ttlMs]),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic>? getLinkToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getLinkToken, [token]),
            returnValueForMissingStub: null,
          )
          as Map<String, dynamic>?);

  @override
  void deleteLinkToken(String? token) => super.noSuchMethod(
    Invocation.method(#deleteLinkToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  int getReputation(String? entityId) =>
      (super.noSuchMethod(
            Invocation.method(#getReputation, [entityId]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void updateReputation(String? entityId, int? delta) => super.noSuchMethod(
    Invocation.method(#updateReputation, [entityId, delta]),
    returnValueForMissingStub: null,
  );

  @override
  bool isWhitelisted(String? id, String? type) =>
      (super.noSuchMethod(
            Invocation.method(#isWhitelisted, [id, type]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void writeAudit(String? event, Map<String, dynamic>? meta) =>
      super.noSuchMethod(
        Invocation.method(#writeAudit, [event, meta]),
        returnValueForMissingStub: null,
      );

  @override
  void pruneExpiredData() => super.noSuchMethod(
    Invocation.method(#pruneExpiredData, []),
    returnValueForMissingStub: null,
  );

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );

  @override
  int countBindingsForGardener(String? gardenerId) =>
      (super.noSuchMethod(
            Invocation.method(#countBindingsForGardener, [gardenerId]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int countBindingsForSeedling(String? seedlingId) =>
      (super.noSuchMethod(
            Invocation.method(#countBindingsForSeedling, [seedlingId]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<Map<String, dynamic>> getBindings(String? entityId) =>
      (super.noSuchMethod(
            Invocation.method(#getBindings, [entityId]),
            returnValue: <Map<String, dynamic>>[],
            returnValueForMissingStub: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  String? getOwnerForDevice(String? seedlingId) =>
      (super.noSuchMethod(
            Invocation.method(#getOwnerForDevice, [seedlingId]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  List<Map<String, dynamic>> getUserActivity(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserActivity, [userId]),
            returnValue: <Map<String, dynamic>>[],
            returnValueForMissingStub: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>>? getScrapCache(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getScrapCache, [id]),
            returnValueForMissingStub: null,
          )
          as List<Map<String, dynamic>>?);

  @override
  void setScrapCache(String? id, List<Map<String, dynamic>>? results) =>
      super.noSuchMethod(
        Invocation.method(#setScrapCache, [id, results]),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic>? getUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [id]),
            returnValueForMissingStub: null,
          )
          as Map<String, dynamic>?);

  @override
  void upsertUser({
    required String? id,
    required String? email,
    required String? provider,
    Map<String, dynamic>? settings,
  }) => super.noSuchMethod(
    Invocation.method(#upsertUser, [], {
      #id: id,
      #email: email,
      #provider: provider,
      #settings: settings,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void updateUserSettings(String? id, Map<String, dynamic>? newSettings) =>
      super.noSuchMethod(
        Invocation.method(#updateUserSettings, [id, newSettings]),
        returnValueForMissingStub: null,
      );

  @override
  void deleteUser(String? id) => super.noSuchMethod(
    Invocation.method(#deleteUser, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteUserBindings(String? userId) => super.noSuchMethod(
    Invocation.method(#deleteUserBindings, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteBinding(String? gardenerId, String? seedlingId) =>
      super.noSuchMethod(
        Invocation.method(#deleteBinding, [gardenerId, seedlingId]),
        returnValueForMissingStub: null,
      );

  @override
  T transaction<T>(T Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action]),
            returnValue: _i3.dummyValue<T>(
              this,
              Invocation.method(#transaction, [action]),
            ),
            returnValueForMissingStub: _i3.dummyValue<T>(
              this,
              Invocation.method(#transaction, [action]),
            ),
          )
          as T);
}

/// A class which mocks [HealthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHealthService extends _i1.Mock implements _i4.HealthService {
  @override
  _i5.Future<bool> checkHealthy(String? urlStr, {bool? aggressive = false}) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkHealthy,
              [urlStr],
              {#aggressive: aggressive},
            ),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> checkUdpTracker(
    String? trackerUrl, {
    Duration? timeout = const Duration(seconds: 5),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkUdpTracker,
              [trackerUrl],
              {#timeout: timeout},
            ),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
